# Generated by Django 2.2.2 on 2019-06-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('processes', models.FileField(blank=True, upload_to='')),
                ('status', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
