# Generated by Django 2.2.2 on 2019-06-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='collection',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
